// Stock logo service using multiple public logo APIs with fallback chain

// Map tickers to their domain for logo fetching
const TICKER_DOMAINS: Record<string, string> = {
  // ===== S&P 500 COMPLETE DOMAIN MAPPINGS =====
  // Information Technology
  AAPL: 'apple.com',
  MSFT: 'microsoft.com',
  NVDA: 'nvidia.com',
  AVGO: 'broadcom.com',
  ORCL: 'oracle.com',
  CRM: 'salesforce.com',
  AMD: 'amd.com',
  ADBE: 'adobe.com',
  CSCO: 'cisco.com',
  IBM: 'ibm.com',
  QCOM: 'qualcomm.com',
  TXN: 'ti.com',
  NOW: 'servicenow.com',
  INTC: 'intel.com',
  PANW: 'paloaltonetworks.com',
  PLTR: 'palantir.com',
  CRWD: 'crowdstrike.com',
  ANET: 'arista.com',
  INTU: 'intuit.com',
  AMAT: 'appliedmaterials.com',
  ADI: 'analog.com',
  KLAC: 'kla.com',
  LRCX: 'lamresearch.com',
  SNPS: 'synopsys.com',
  CDNS: 'cadence.com',
  FTNT: 'fortinet.com',
  MRVL: 'marvell.com',
  MSI: 'motorolasolutions.com',
  APH: 'amphenol.com',
  NXPI: 'nxp.com',
  ON: 'onsemi.com',
  MU: 'micron.com',
  FICO: 'fico.com',
  IT: 'gartner.com',
  MPWR: 'monolithicpower.com',
  KEYS: 'keysight.com',
  DELL: 'dell.com',
  HPQ: 'hp.com',
  HPE: 'hpe.com',
  GLW: 'corning.com',
  ZBRA: 'zebra.com',
  CDW: 'cdw.com',
  TDY: 'teledyne.com',
  TYL: 'tylertech.com',
  TRMB: 'trimble.com',
  SMCI: 'supermicro.com',
  GDDY: 'godaddy.com',
  GEN: 'gendigital.com',
  FSLR: 'firstsolar.com',
  EPAM: 'epam.com',
  VRSN: 'verisign.com',
  SWKS: 'skyworksinc.com',
  JNPR: 'juniper.net',
  FFIV: 'f5.com',
  QRVO: 'qorvo.com',
  WDAY: 'workday.com',
  TEAM: 'atlassian.com',
  HUBS: 'hubspot.com',
  TTD: 'thetradedesk.com',
  SHOP: 'shopify.com',
  SNOW: 'snowflake.com',
  NET: 'cloudflare.com',
  DDOG: 'datadoghq.com',
  ZS: 'zscaler.com',
  MDB: 'mongodb.com',
  TWLO: 'twilio.com',
  OKTA: 'okta.com',
  DOCU: 'docusign.com',
  PATH: 'uipath.com',
  ENPH: 'enphase.com',
  SEDG: 'solaredge.com',
  ARM: 'arm.com',
  U: 'unity.com',
  // Communication Services
  GOOGL: 'google.com',
  META: 'meta.com',
  NFLX: 'netflix.com',
  DIS: 'disney.com',
  TMUS: 't-mobile.com',
  T: 'att.com',
  VZ: 'verizon.com',
  CMCSA: 'comcast.com',
  CHTR: 'spectrum.com',
  EA: 'ea.com',
  TTWO: 'take2games.com',
  WBD: 'wbd.com',
  PARA: 'banzai.io',
  OMC: 'omnicomgroup.com',
  IPG: 'interpublic.com',
  NWSA: 'newscorp.com',
  MTCH: 'mtch.com',
  LYV: 'livenationentertainment.com',
  FOXA: 'foxcorporation.com',
  SNAP: 'snap.com',
  PINS: 'pinterest.com',
  ZM: 'zoom.us',
  SPOT: 'spotify.com',
  ROKU: 'roku.com',
  RBLX: 'roblox.com',
  AMC: 'amctheatres.com',
  SE: 'sea.com',
  // Consumer Discretionary
  AMZN: 'amazon.com',
  TSLA: 'tesla.com',
  HD: 'homedepot.com',
  MCD: 'mcdonalds.com',
  NKE: 'nike.com',
  LOW: 'lowes.com',
  SBUX: 'starbucks.com',
  TJX: 'tjx.com',
  BKNG: 'booking.com',
  ABNB: 'airbnb.com',
  CMG: 'chipotle.com',
  ORLY: 'oreillyauto.com',
  AZO: 'autozone.com',
  MAR: 'marriott.com',
  HLT: 'hilton.com',
  ROST: 'rossstores.com',
  GM: 'gm.com',
  F: 'ford.com',
  DHI: 'drhorton.com',
  LEN: 'lennar.com',
  PHM: 'pultegroup.com',
  NVR: 'nvrinc.com',
  GPC: 'genpt.com',
  LULU: 'lululemon.com',
  POOL: 'poolcorp.com',
  ULTA: 'ulta.com',
  DKNG: 'draftkings.com',
  EBAY: 'ebay.com',
  ETSY: 'etsy.com',
  YUM: 'yum.com',
  DPZ: 'dominos.com',
  DECK: 'deckers.com',
  RCL: 'royalcaribbean.com',
  CCL: 'carnival.com',
  NCLH: 'ncl.com',
  EXPE: 'expediagroup.com',
  LVS: 'sands.com',
  MGM: 'mgmresorts.com',
  WYNN: 'wynnresorts.com',
  BBY: 'bestbuy.com',
  TSCO: 'tractorsupply.com',
  KMX: 'carmax.com',
  APTV: 'aptiv.com',
  BWA: 'borgwarner.com',
  CZR: 'caesars.com',
  HAS: 'hasbro.com',
  MHK: 'mohawkind.com',
  GRMN: 'garmin.com',
  TPR: 'tapestry.com',
  RL: 'ralphlauren.com',
  DASH: 'doordash.com',
  W: 'wayfair.com',
  CHWY: 'chewy.com',
  RIVN: 'rivian.com',
  LCID: 'lucidmotors.com',
  MELI: 'mercadolibre.com',
  GME: 'gamestop.com',
  NIO: 'nio.com',
  LI: 'lixiang.com',
  XPEV: 'xpeng.com',
  TM: 'toyota.com',
  // Consumer Staples
  WMT: 'walmart.com',
  COST: 'costco.com',
  PG: 'pg.com',
  KO: 'coca-cola.com',
  PEP: 'pepsico.com',
  PM: 'pmi.com',
  MO: 'altria.com',
  MDLZ: 'mondelezinternational.com',
  CL: 'colgatepalmolive.com',
  TGT: 'target.com',
  STZ: 'cbrands.com',
  SYY: 'sysco.com',
  GIS: 'generalmills.com',
  KMB: 'kimberly-clark.com',
  ADM: 'adm.com',
  HSY: 'thehersheycompany.com',
  K: 'kellanova.com',
  EL: 'esteelauder.com',
  KR: 'kroger.com',
  MNST: 'monsterbevcorp.com',
  CAG: 'conagra.com',
  SJM: 'jmsmucker.com',
  MKC: 'mccormick.com',
  CHD: 'churchdwight.com',
  CLX: 'clorox.com',
  KDP: 'keurigdrpepper.com',
  TAP: 'molsoncoors.com',
  CPB: 'campbellsoupcompany.com',
  BG: 'bunge.com',
  LW: 'lambweston.com',
  // Financials
  JPM: 'jpmorganchase.com',
  V: 'visa.com',
  MA: 'mastercard.com',
  BAC: 'bankofamerica.com',
  WFC: 'wellsfargo.com',
  GS: 'goldmansachs.com',
  MS: 'morganstanley.com',
  BLK: 'blackrock.com',
  C: 'citigroup.com',
  AXP: 'americanexpress.com',
  SCHW: 'schwab.com',
  PYPL: 'paypal.com',
  SPGI: 'spglobal.com',
  MCO: 'moodys.com',
  MMC: 'marshmclennan.com',
  PGR: 'progressive.com',
  CB: 'chubb.com',
  AON: 'aon.com',
  ICE: 'ice.com',
  CME: 'cmegroup.com',
  USB: 'usbank.com',
  PNC: 'pnc.com',
  TFC: 'truist.com',
  AIG: 'aig.com',
  MET: 'metlife.com',
  PRU: 'prudential.com',
  ALL: 'allstate.com',
  AFL: 'aflac.com',
  TRV: 'travelers.com',
  AJG: 'ajg.com',
  MSCI: 'msci.com',
  FI: 'fiserv.com',
  COF: 'capitalone.com',
  DFS: 'discover.com',
  SYF: 'synchrony.com',
  FITB: '53.com',
  KEY: 'key.com',
  HBAN: 'huntington.com',
  RF: 'regions.com',
  CFG: 'citizensbank.com',
  MTB: 'mtb.com',
  NTRS: 'northerntrust.com',
  CINF: 'cinfin.com',
  L: 'loews.com',
  BRO: 'bbinsurance.com',
  RE: 'everestgroup.com',
  WRB: 'berkley.com',
  GL: 'globelifeinsurance.com',
  FDS: 'factset.com',
  NDAQ: 'nasdaq.com',
  CBOE: 'cboe.com',
  COIN: 'coinbase.com',
  SQ: 'squareup.com',
  SOFI: 'sofi.com',
  HOOD: 'robinhood.com',
  'BRK.B': 'berkshirehathaway.com',
  ACGL: 'archgroup.com',
  // Healthcare
  UNH: 'unitedhealthgroup.com',
  LLY: 'lilly.com',
  JNJ: 'jnj.com',
  ABBV: 'abbvie.com',
  MRK: 'merck.com',
  TMO: 'thermofisher.com',
  ABT: 'abbott.com',
  PFE: 'pfizer.com',
  AMGN: 'amgen.com',
  BMY: 'bms.com',
  ISRG: 'intuitive.com',
  GILD: 'gilead.com',
  VRTX: 'vrtx.com',
  REGN: 'regeneron.com',
  SYK: 'stryker.com',
  BDX: 'bd.com',
  MDT: 'medtronic.com',
  CI: 'thecignagroup.com',
  ELV: 'elevancehealth.com',
  HUM: 'humana.com',
  CNC: 'centene.com',
  MCK: 'mckesson.com',
  ZTS: 'zoetis.com',
  BSX: 'bostonscientific.com',
  EW: 'edwards.com',
  IDXX: 'idexx.com',
  DXCM: 'dexcom.com',
  IQV: 'iqvia.com',
  A: 'agilent.com',
  DHR: 'danaher.com',
  RMD: 'resmed.com',
  CAH: 'cardinalhealth.com',
  COR: 'cencora.com',
  BAX: 'baxter.com',
  MRNA: 'modernatx.com',
  BIIB: 'biogen.com',
  VEEV: 'veeva.com',
  HOLX: 'hologic.com',
  MTD: 'mt.com',
  WAT: 'waters.com',
  ALGN: 'aligntech.com',
  TECH: 'bio-techne.com',
  VTRS: 'viatris.com',
  MOH: 'molinahealthcare.com',
  INCY: 'incyte.com',
  RVTY: 'revvity.com',
  HSIC: 'henryschein.com',
  DGX: 'questdiagnostics.com',
  LH: 'labcorp.com',
  NVO: 'novonordisk.com',
  // Industrials
  GE: 'geaerospace.com',
  CAT: 'caterpillar.com',
  HON: 'honeywell.com',
  UPS: 'ups.com',
  RTX: 'rtx.com',
  BA: 'boeing.com',
  DE: 'deere.com',
  LMT: 'lockheedmartin.com',
  UNP: 'up.com',
  ETN: 'eaton.com',
  ADP: 'adp.com',
  WM: 'wm.com',
  FDX: 'fedex.com',
  GD: 'gd.com',
  NOC: 'northropgrumman.com',
  ITW: 'itw.com',
  EMR: 'emerson.com',
  CSX: 'csx.com',
  NSC: 'norfolksouthern.com',
  CPRT: 'copart.com',
  CTAS: 'cintas.com',
  PAYX: 'paychex.com',
  FAST: 'fastenal.com',
  UBER: 'uber.com',
  RSG: 'republicservices.com',
  PCAR: 'paccar.com',
  VRSK: 'verisk.com',
  GWW: 'grainger.com',
  IR: 'irco.com',
  PWR: 'quantaservices.com',
  AME: 'ametek.com',
  ROK: 'rockwellautomation.com',
  AXON: 'axon.com',
  TT: 'tranetechnologies.com',
  XYL: 'xylem.com',
  HWM: 'howmet.com',
  DOV: 'dovercorporation.com',
  ROP: 'ropertech.com',
  SWK: 'stanleyblackanddecker.com',
  J: 'jacobs.com',
  HUBB: 'hubbell.com',
  DAL: 'delta.com',
  UAL: 'united.com',
  LUV: 'southwest.com',
  WAB: 'wabteccorp.com',
  LDOS: 'leidos.com',
  IEX: 'idexcorp.com',
  PNR: 'pentair.com',
  NDSN: 'nordson.com',
  PAYC: 'paycom.com',
  GNRC: 'generac.com',
  // Energy
  XOM: 'exxonmobil.com',
  CVX: 'chevron.com',
  COP: 'conocophillips.com',
  SLB: 'slb.com',
  EOG: 'eogresources.com',
  OXY: 'oxy.com',
  MPC: 'marathonpetroleum.com',
  PSX: 'phillips66.com',
  VLO: 'valero.com',
  PXD: 'pxd.com',
  WMB: 'williams.com',
  KMI: 'kindermorgan.com',
  OKE: 'oneok.com',
  HAL: 'halliburton.com',
  FANG: 'diamondbackenergy.com',
  DVN: 'devonenergy.com',
  BKR: 'bakerhughes.com',
  HES: 'hess.com',
  CTRA: 'coterra.com',
  TRGP: 'targaresources.com',
  EQT: 'eqt.com',
  APA: 'apacorp.com',
  SHEL: 'shell.com',
  BP: 'bp.com',
  // Utilities
  NEE: 'nexteraenergy.com',
  DUK: 'duke-energy.com',
  SO: 'southerncompany.com',
  D: 'dominionenergy.com',
  SRE: 'sempra.com',
  AEP: 'aep.com',
  EXC: 'exeloncorp.com',
  XEL: 'xcelenergy.com',
  ED: 'conedison.com',
  WEC: 'wecenergygroup.com',
  ES: 'eversource.com',
  PCG: 'pgecorp.com',
  AWK: 'amwater.com',
  DTE: 'dteenergy.com',
  EIX: 'edison.com',
  FE: 'firstenergycorp.com',
  ETR: 'entergy.com',
  PPL: 'pplweb.com',
  AEE: 'ameren.com',
  CMS: 'cmsenergy.com',
  CNP: 'centerpointenergy.com',
  ATO: 'atmosenergy.com',
  NI: 'nisource.com',
  LNT: 'alliantenergy.com',
  EVRG: 'evergy.com',
  PNW: 'pinnaclewest.com',
  // Real Estate
  AMT: 'americantower.com',
  PLD: 'prologis.com',
  CCI: 'crowncastle.com',
  EQIX: 'equinix.com',
  SPG: 'simon.com',
  PSA: 'publicstorage.com',
  O: 'realtyincome.com',
  WELL: 'welltower.com',
  DLR: 'digitalrealty.com',
  VICI: 'vfreit.com',
  SBAC: 'sbasite.com',
  AVB: 'avalonbay.com',
  EQR: 'equityapartments.com',
  WY: 'weyerhaeuser.com',
  ARE: 'are.com',
  MAA: 'maac.com',
  EXR: 'extraspace.com',
  ESS: 'essexapartmenthomes.com',
  IRM: 'ironmountain.com',
  VTR: 'ventasreit.com',
  INVH: 'invitationhomes.com',
  HST: 'hosthotels.com',
  KIM: 'kimcorealty.com',
  REG: 'regencycenters.com',
  CPT: 'camdenliving.com',
  UDR: 'udr.com',
  BXP: 'bxp.com',
  // Materials
  LIN: 'linde.com',
  APD: 'airproducts.com',
  SHW: 'sherwin-williams.com',
  ECL: 'ecolab.com',
  FCX: 'fcx.com',
  NEM: 'newmont.com',
  NUE: 'nucor.com',
  VMC: 'vulcanmaterials.com',
  MLM: 'martinmarietta.com',
  DOW: 'dow.com',
  DD: 'dupont.com',
  PPG: 'ppg.com',
  IFF: 'iff.com',
  ALB: 'albemarle.com',
  CE: 'celanese.com',
  EMN: 'eastman.com',
  PKG: 'packagingcorp.com',
  IP: 'internationalpaper.com',
  BALL: 'ball.com',
  AMCR: 'amcor.com',
  CF: 'cfindustries.com',
  MOS: 'mosaicco.com',
  STLD: 'steeldynamics.com',
  // Additional popular
  MSTR: 'microstrategy.com',
  MARA: 'mara.com',
  RIOT: 'riotplatforms.com',
  BABA: 'alibaba.com',
  TSM: 'tsmc.com',
  ASML: 'asml.com',
  SAP: 'sap.com',
  SONY: 'sony.com',
  GRAB: 'grab.com',
  AI: 'c3.ai',
  IONQ: 'ionq.com',
  RGTI: 'rigetti.com',
  // Expanded stock list domains
  BILL: 'bill.com',
  CFLT: 'confluent.io',
  ESTC: 'elastic.co',
  GTLB: 'gitlab.com',
  PCOR: 'procore.com',
  QLYS: 'qualys.com',
  RPD: 'rapid7.com',
  SMAR: 'smartsheet.com',
  TENB: 'tenable.com',
  VRNS: 'varonis.com',
  WK: 'workiva.com',
  APPF: 'appfolio.com',
  BSY: 'bentley.com',
  CWAN: 'clearwateranalytics.com',
  FOUR: 'shift4.com',
  FRSH: 'freshworks.com',
  JAMF: 'jamf.com',
  MANH: 'manh.com',
  NCNO: 'ncino.com',
  NICE: 'nice.com',
  PCTY: 'paylocity.com',
  PI: 'impinj.com',
  PSTG: 'purestorage.com',
  RELY: 'remitly.com',
  S: 'sentinelone.com',
  SSNC: 'ssctech.com',
  TASK: 'taskus.com',
  VNT: 'vontier.com',
  WOLF: 'wolfspeed.com',
  BMBL: 'bumble.com',
  BROS: 'dutchbros.com',
  CAVA: 'cava.com',
  SHAK: 'shakeshack.com',
  WING: 'wingstop.com',
  TXRH: 'texasroadhouse.com',
  EAT: 'bfrands.com',
  DRI: 'darden.com',
  PENN: 'pennentertainment.com',
  BURL: 'burlington.com',
  GAP: 'gap.com',
  ANF: 'abercrombie.com',
  SKX: 'skechers.com',
  COLM: 'columbia.com',
  VFC: 'vfc.com',
  PVH: 'pvh.com',
  BOOT: 'bootbarn.com',
  ONON: 'on-running.com',
  LEVI: 'levistrauss.com',
  AFRM: 'affirm.com',
  UPST: 'upstart.com',
  LC: 'lendingclub.com',
  NU: 'nubank.com.br',
  MKTX: 'marketaxess.com',
  LPLA: 'lpl.com',
  RJF: 'raymondjames.com',
  IBKR: 'interactivebrokers.com',
  TROW: 'troweprice.com',
  BEN: 'franklintempleton.com',
  IVZ: 'invesco.com',
  ALLY: 'ally.com',
  EWBC: 'eastwestbank.com',
  ZION: 'zionsbancorporation.com',
  CMA: 'comerica.com',
  WAL: 'westernalliancebancorporation.com',
  EXAS: 'exactsciences.com',
  HALO: 'halozyme.com',
  IONS: 'ionispharma.com',
  JAZZ: 'jazzpharma.com',
  NBIX: 'neurocrine.com',
  ALNY: 'alnylam.com',
  ARGX: 'argenx.com',
  BIO: 'bio-rad.com',
  BMRN: 'biomarin.com',
  CRL: 'criver.com',
  GH: 'guardanthealth.com',
  ILMN: 'illumina.com',
  INSM: 'insmed.com',
  LNTH: 'lantheus.com',
  MEDP: 'medpace.com',
  MASI: 'masimo.com',
  SRPT: 'sarepta.com',
  JOBY: 'jobyaviation.com',
  BLDE: 'blade.com',
  WCN: 'wasteconnections.com',
  CLH: 'cleanharbors.com',
  TTC: 'thetorocompany.com',
  FLR: 'fluor.com',
  BWXT: 'bwxt.com',
  HEI: 'heico.com',
  TDG: 'transdigm.com',
  CARR: 'carrier.com',
  OTIS: 'otis.com',
  VLTO: 'veralto.com',
  AR: 'anteroresources.com',
  RRC: 'rangeresources.com',
  MTDR: 'matadorresources.com',
  CNX: 'cnx.com',
  USFD: 'usfoods.com',
  SAM: 'bostonbeer.com',
  POST: 'postholdings.com',
  CBRE: 'cbre.com',
  JLL: 'jll.com',
  RS: 'rsac.com',
  JD: 'jd.com',
  PDD: 'pinduoduo.com',
  BIDU: 'baidu.com',
  NTES: 'netease.com',
  BILI: 'bilibili.com',
  FUTU: 'futuholdings.com',
  DEO: 'diageo.com',
  UL: 'unilever.com',
  AZN: 'astrazeneca.com',
  GSK: 'gsk.com',
  SNY: 'sanofi.com',
  HSBC: 'hsbc.com',
  BCS: 'barclays.com',
  DB: 'db.com',
  UBS: 'ubs.com',
  TTE: 'totalenergies.com',
  EQNR: 'equinor.com',
  RIO: 'riotinto.com',
  BHP: 'bhp.com',
  VALE: 'vale.com',
  WPM: 'wheatonpm.com',
  GOLD: 'barrick.com',
  AEM: 'agnicoeagle.com',
  VST: 'vistracorp.com',
  CEG: 'constellationenergy.com',
  NRG: 'nrg.com',
  SPY: 'ssga.com',
  QQQ: 'invesco.com',
  ARKK: 'ark-invest.com',
  CYBR: 'cyberark.com',
  FVRR: 'fiverr.com',
  UPWK: 'upwork.com',
  ASAN: 'asana.com',
  DOCN: 'digitalocean.com',
  AYX: 'alteryx.com',
  DBX: 'dropbox.com',
  BOX: 'box.com',
  CIEN: 'ciena.com',
  OLED: 'oled.com',
  SOUN: 'soundhound.ai',
  ASTS: 'ast-science.com',
  CLSK: 'cleanspark.com',
  VKTX: 'vikingtherapeutics.com',
  BEAM: 'beamtx.com',
  NTLA: 'intelliatx.com',
  CYTK: 'cytokinetics.com',
  RPRX: 'royaltypharma.com',
  TGTX: 'tgtherapeutics.com',
  TWST: 'twistbioscience.com',
  DNA: 'ginkgobioworks.com',
  // Additional S&P 500 & popular tickers
  ABNB: 'airbnb.com',
  ACHR: 'archer.com',
  APP: 'applovin.com',
  BIRK: 'birkenstock.com',
  CELH: 'celsius.com',
  CRSP: 'crisprtx.com',
  CROX: 'crocs.com',
  CVNA: 'carvana.com',
  DNUT: 'krispykreme.com',
  DT: 'dynatrace.com',
  DUOL: 'duolingo.com',
  FIVE: 'fivebelow.com',
  FIVN: 'five9.com',
  GLOB: 'globant.com',
  HCP: 'hashicorp.com',
  HOOD: 'robinhood.com',
  IOT: 'samsara.com',
  KHC: 'kraftheinzcompany.com',
  KVUE: 'kenvue.com',
  LLY: 'lilly.com',
  LSCC: 'latticesemi.com',
  LYFT: 'lyft.com',
  MARA: 'mara.com',
  MNDY: 'monday.com',
  MSCI: 'msci.com',
  NTNX: 'nutanix.com',
  NTRA: 'natera.com',
  OWL: 'blueowl.com',
  PANW: 'paloaltonetworks.com',
  PCVX: 'vfreit.com',
  RKLB: 'rocketlabusa.com',
  RUN: 'sunrun.com',
  SIRI: 'siriusxm.com',
  SMCI: 'supermicro.com',
  TOST: 'toasttab.com',
  TW: 'tradeweb.com',
  TWST: 'twistbioscience.com',
  VST: 'vistracorp.com',
  WBX: 'wallboxchargers.com',
  ZI: 'zoominfo.com',
  ZTO: 'zto.com',
};

// Cache resolved URLs to avoid repeated lookups
const urlCache = new Map<string, string>();
const altUrlCache = new Map<string, string>();
// Session 175 — module-level Set that remembers which logo URLs have
// already been asked to prefetch this session so batch prefetch calls
// from multiple components (Home, Signals, StockCard mount) don't fire
// duplicate Image.prefetch requests. Cleared automatically when the app
// reloads (expo-image's memory-disk cache persists across launches, so
// the OS still returns from cache on the next session even if we re-add).
const prefetchedUrls = new Set<string>();

// Session 176 — background warming of the built-in stock universe. Fired
// ONCE per app session after critical startup work is done. Uses a hard
// concurrency cap so we never hammer Clearbit / Google favicons with
// hundreds of parallel requests.
let universeWarmingStarted = false;

export type LogoPrefetchPriority = 'high' | 'normal' | 'background';

// Simple concurrency-limited runner. We deliberately do not use
// Promise.all across all URLs because that would blast the network with
// hundreds of parallel requests when warming the universe.
async function prefetchWithConcurrency(urls: string[], concurrency: number): Promise<void> {
  if (urls.length === 0) return;
  const { Image } = await import('expo-image');
  let idx = 0;
  const worker = async () => {
    while (idx < urls.length) {
      const url = urls[idx++];
      try { await Image.prefetch(url); } catch { /* swallow single-URL failure */ }
    }
  };
  const workers = Array.from({ length: Math.max(1, Math.min(concurrency, urls.length)) }, () => worker());
  await Promise.all(workers);
}

/**
 * Session 175/176 — batch prefetch stock logos into memory-disk cache.
 * Call this the moment a list of tickers becomes known (watchlist load,
 * AI signals load, search results, active trades) so images are already
 * resolved by the time each card mounts.
 *
 * Priority controls how aggressively we prefetch:
 *   - 'high'       (default): user's own tickers — primary + alternate URL,
 *                             8-way concurrency, small batches.
 *   - 'normal'                 visible search / trending — primary only,
 *                             4-way concurrency.
 *   - 'background'             built-in universe warm — primary only,
 *                             2-way concurrency, tolerant of failures.
 *
 * All calls dedupe against the session Set so re-adding a ticker is a
 * no-op. Failures are swallowed — prefetch is best-effort.
 */
export async function prefetchLogos(
  tickers: readonly string[],
  priority: LogoPrefetchPriority = 'high',
): Promise<void> {
  if (!Array.isArray(tickers) || tickers.length === 0) return;
  const urls: string[] = [];
  for (const t of tickers) {
    if (!t) continue;
    const primary = getStockLogoUrl(t);
    if (primary && !prefetchedUrls.has(primary)) { prefetchedUrls.add(primary); urls.push(primary); }
    // Only include the alternate favicon URL for high-priority (user's
    // own) tickers. Background warming only needs the primary URL so we
    // don't double the outbound request count.
    if (priority === 'high') {
      const alt = getAlternateLogoUrl(t);
      if (alt && !prefetchedUrls.has(alt)) { prefetchedUrls.add(alt); urls.push(alt); }
    }
  }
  if (urls.length === 0) return;
  const concurrency = priority === 'high' ? 8 : priority === 'normal' ? 4 : 2;
  try {
    await prefetchWithConcurrency(urls, concurrency);
  } catch { /* swallow — prefetch is best-effort */ }
}

// Session 214 — also warm the trending stock universe (search modal
// content) on mount so opening the search UI shows crisp logos with
// zero flicker. This complements watchlist / portfolio prefetch which
// only covers user-selected tickers.
const TRENDING_STOCKS = ['NVDA', 'AAPL', 'TSLA', 'MSFT', 'AMZN', 'META', 'GOOGL', 'NFLX', 'AMD', 'COIN', 'PLTR', 'UBER'];

/**
 * Session 176 — warm the built-in stock universe in the background so
 * repeat visits to any stock are effectively instant. Called by Home
 * once after critical startup work (post-mount, post-first-render).
 * Runs at most ONCE per app session. Uses 'background' priority with a
 * concurrency cap of 2 so it doesn't compete with foreground network
 * work like quote fetches or broker syncs.
 *
 * This function intentionally does NOT bundle logos into the app binary
 * (which would bloat the download and let logos go stale). It relies on
 * expo-image's persistent memory-disk cache to make second and later
 * launches feel instant.
 */
export async function warmLogoUniverse(): Promise<void> {
  if (universeWarmingStarted) return;
  universeWarmingStarted = true;
  // Session 214 — warm TRENDING first at 'normal' priority (so the
  // search modal is instant on first open), then queue the full
  // universe at 'background' priority. Trending stocks are prefetched
  // before yielding to the JS thread so the modal always feels instant.
  await prefetchLogos(TRENDING_STOCKS, 'normal').catch(() => {});
  const tickers = Object.keys(TICKER_DOMAINS);
  await new Promise((resolve) => setTimeout(resolve, 800));
  await prefetchLogos(tickers, 'background');
}

export function getStockLogoUrl(ticker: string): string {
  const cached = urlCache.get(ticker);
  if (cached) return cached;
  const domain = TICKER_DOMAINS[ticker];
  // Use Clearbit as primary (higher quality logos)
  const url = domain
    ? `https://logo.clearbit.com/${domain}`
    : `https://logo.clearbit.com/${ticker.toLowerCase()}.com`;
  urlCache.set(ticker, url);
  return url;
}

export function getAlternateLogoUrl(ticker: string): string {
  const cached = altUrlCache.get(ticker);
  if (cached) return cached;
  const domain = TICKER_DOMAINS[ticker];
  // Use Google favicons as fallback with max size
  const url = domain
    ? `https://www.google.com/s2/favicons?domain=${domain}&sz=128`
    : `https://www.google.com/s2/favicons?domain=${ticker.toLowerCase()}.com&sz=128`;
  altUrlCache.set(ticker, url);
  return url;
}

export function getTickerColor(ticker: string): string {
  const colors = ['#3B82F6', '#10B981', '#F59E0B', '#EF4444', '#8B5CF6', '#EC4899', '#06B6D4', '#F97316'];
  const index = ticker.charCodeAt(0) % colors.length;
  return colors[index];
}
